server:
  port: 9201
  servlet:
    context-path: ""

spring:
  profiles:
    active: "dev"
  application:
    name: gateway

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.ict.entity