server:
  port: 9301
  servlet:
    context-path: ""

spring:
  profiles:
    active: "dev"
  application:
    name: loginserver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ict.login.entity