server:
  port: 9302
  servlet:
    context-path: ""

spring:
  profiles:
    active: "dev"
  application:
    name: usercenter

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ict.entity
